name: MySQL 8.0 Build and Run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy MySQL
        run: scripts/dbdeployer_install_8028.sh

      - name: Build and Run
        run: go build ./cmd/spirit
        ~/sandboxes/msb_8_0_28/use test -e "CREATE TABLE t1 (id INT NOT NULL PRIMARY KEY auto_increment, b INT NOT NULL, c INT NOT NULL)"
        ./cmd/spirit/spirit -h "127.0.0.1:8028" --database=test --table=stock
