name: MySQL 8.4 GA
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.23
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy MySQL
        run: scripts/manual_install_84.sh && mysql -u root -h 127.0.0.1 -P 3306 -e "CREATE DATABASE test;"

      - name: Test
        run: MYSQL_DSN="root:@tcp(127.0.0.1:3306)/test" REPLICA_DSN="root:@tcp(127.0.0.1:3307)/test" go test  -race -v ./...
