name: MySQL 8.4 GA
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy MySQL
        run: scripts/manual_install_84.sh
             mysql -P 22334 -u root -e "CREATE DATABASE test;"

      - name: Test
        run: MYSQL_DSN="root:@tcp(127.0.0.1:22334)/test" go test  -race -v ./...
