name: MySQL 5.7.34 (with replicas)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Init Hermit
        run: ./bin/hermit env -r >> $GITHUB_ENV

      - name: Deploy MySQL
        run: scripts/dbdeployer_install_57.sh

      - name: Test
        run: MYSQL_DSN="msandbox:msandbox@tcp(127.0.0.1:20135)/test" REPLICA_DSN="msandbox:msandbox@tcp(127.0.0.1:20136)/test" go test  -race -v ./...
