name: MySQL 8.2 innovation release
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy MySQL
        run: scripts/dbdeployer_install_82.sh

      - name: Test
        run: MYSQL_DSN="msandbox:msandbox@tcp(127.0.0.1:8200)/test" go test  -race -v ./...
